### ISSUE TITLE
Why does the map offset when zooming out?

### ISSUE THREAD

**Issue by echohye** [manimaul/njord#36]
Hello, thank you very much for this project. However,  I've got the problem in the picture. As shown in the picture, why does the map offset when I zoom in and out. Do you have any solution ? Thanks in advance.
![image](https://github.com/manimaul/njord/assets/81301702/7f43f903-f2ba-46d5-9662-5ba846e7979a)

**Comment by manimaul** [comment]
@echohye My guess would be an error in the source data. Can you load the S57 source data into OpenCPN and check what happens there? 

The red chart outling [(PLY) layer](https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/layers/Ply.kt) is calculated using the M_COVR geometry:

Here is where the geometry is encoded into the tile:
https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/geo/TileEncoder.kt#L81
https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/geo/TileEncoder.kt#L105-L110

Here is where M_COVR with CATCOV==1 is read:
https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/geo/S57.kt#L67-L69

Info on M_COVR:
https://openenc.com/control/symbols/M_COVR/CATCOV

**Comment by echohye** [comment]
> @echohye My guess would be an error in the source data. Can you load the S57 source data into OpenCPN and check what happens there?
> 
> The red chart outling [(PLY) layer](https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/layers/Ply.kt) is calculated using the M_COVR geometry:
> 
> Here is where the geometry is encoded into the tile: https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/geo/TileEncoder.kt#L81 https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/geo/TileEncoder.kt#L105-L110
> 
> Here is where M_COVR with CATCOV==1 is read: https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/geo/S57.kt#L67-L69
> 
> Info on M_COVR: https://openenc.com/control/symbols/M_COVR/CATCOV

This is an example data. Based on the element fid query in the database, I found that they are the same feature. At lower zoom levels, they may offset, while at higher zoom levels, they may overlap. I guess there was an issue during the process of querying the data and converting it to PBF format.

**Comment by echohye** [comment]
Also, it can find this issue in https://openenc.com/enc
![image](https://github.com/manimaul/njord/assets/81301702/d7b22ae8-7da7-49c8-918a-903fd81eeee0)

**Comment by echohye** [comment]
At different levels, using Chart Query，click on the query features and it is found that they have the same attributes but different geometries. Copy their JSON data and display it [here](http://geojson.io/). The effect is as follows
![image](https://github.com/manimaul/njord/assets/81301702/21a95e90-4b98-4451-9c4a-c8445ae5a3fb)

**Comment by manimaul** [comment]
Ok, I can replicate this problem looking at any small scale chart zoomed out. I think I have the same chart data GB1B20M4.000 from the UKHO collection. Looking at the geometries in the db example:
```
select layer, st_asgeojson(geom)::JSON from features where chart_id=1;
```
The raw geometries in the db ----^ are fine which is good as those are coming straight from Gdal. 

However, there's definitely a latitude distortion issue in the tile encoding process which I believe is only effecting small scale / very zoomed out tiles. I suspect either the VectorTileEncoder and/or the query is introducing the latitude distortion. https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/db/ChartDao.kt#L91-L101

<img width="1033" alt="Screenshot 2023-09-12 at 11 04 03 PM" src="https://github.com/manimaul/njord/assets/229469/689405e3-a2aa-4ffe-b58d-4c365e538294">

**Comment by echohye** [comment]
So is this problem caused by an error during the conversion of this function([ST_AsMVTGeom](https://postgis.net/docs/ST_AsMVTGeom.html)), or is it caused by a writing error in this class[(TileSystem)](https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/geo/TileSystem.kt), but why does the [ply layer](https://github.com/manimaul/njord/blob/master/chart_server/src/main/kotlin/io/madrona/njord/layers/Ply.kt) not have this problem😂

**Comment by echohye** [comment]
ST_AsMVTGeom supports 3857 by default.
![image](https://github.com/manimaul/njord/assets/81301702/cbb2c997-a327-4320-80fc-54177e595684)

**Comment by manimaul** [comment]
@echohye - did you want to submit a pull request with the proposed fix?
