### ISSUE TITLE
s57 update files

### ISSUE THREAD

**Issue by oliveever** [manimaul/njord#37]
Hello, does this project support updating s57 update files, such as. 001 . 002, etc. If not, will this function be added in the future

**Comment by manimaul** [comment]
Yes, the chart import uses Gdal which does support s57 update files: https://gdal.org/drivers/vector/s57.html

> S-57 update files contain information on how to update a distributed S-57 base data file. The base files normally have the extension .000 while the update files have extensions like .001, .002 and so on. The S-57 reader will normally read and apply all updates files to the in memory version of the base file on the fly. The feature data provided to the application therefore includes all the updates.

**Comment by manimaul** [comment]
.000 is the **base file** and the Gdal s57 driver applies the patch files
> The S-57 reader will normally read and apply all updates files to the in memory version of the base file on the fly. 

Some of  icons are extracted from OpenCPN https://github.com/manimaul/njord/blob/master/docs/reference_material/opencpn/chartsymbolextractor.py

Some are extracted from: HPGL https://github.com/manimaul/njord/tree/master/docs/reference_material/hpgl

Some are are just made from svg:
https://github.com/manimaul/njord/tree/master/sprites
