### ISSUE TITLE
FERYRT - linestring bug

### ISSUE THREAD

**Issue by manimaul** [manimaul/njord#41]
Find out if LineString is present in Chart 18448 and investigate why it is being excluded. 
![Screenshot from 2023-09-16 12-03-05](https://github.com/manimaul/njord/assets/229469/10de9bb2-6d21-4697-b335-2fa02c11d724)
Chart 18453, Chart 18448

**Comment by echohye** [comment]
I found the same situation on this website. Maybe the data itself is like this. I don’t know if the chart plotter will be like this too.
https://www.nauticalcharts.noaa.gov/enconline/enconline.html
![image](https://github.com/manimaul/njord/assets/81301702/dc3d1ae5-f39b-4def-94c9-826fdd6bf89a)

**Comment by manimaul** [comment]
This is a data issue as mentioned by @echohye . NOAA chart USWA10M does not have they FERYRT feature. I'm closing this as non issue.
