### ISSUE TITLE
Layer Symbol Configuration Rules | Question 

### ISSUE THREAD

**Issue by echohye** [manimaul/njord#46]
Hello, I would like to ask how do you know the layer configuration rules, such as how to determine what properties and symbols to configure for this light.
https://github.com/manimaul/njord/blob/05712dc9442d6bf54d166a8f44ffaa92203680a3/chart_server/src/main/kotlin/io/madrona/njord/layers/Lights.kt#L20

**Comment by manimaul** [comment]
@echohye - The light color is encoded in S57 Object "LIGHTS" (layer). Njord has this endpoint: https://openenc.com/control/symbols/LIGHTS/COLOUR which represents the information in a human readable format.
