### ISSUE TITLE
Is this Zoom calculation incorrect?

### ISSUE THREAD

**Issue by echohye** [manimaul/njord#47]
![image](https://github.com/manimaul/njord/assets/81301702/43e05f30-5519-4d2a-a53f-e1f91cb24433)
For example, at level 10, the upper part is not displayed, but it is displayed at level 11. They should be displayed simultaneously. Is this a problem with incorrect level calculation？

![image](https://github.com/manimaul/njord/assets/81301702/e6ba79a3-7902-4c7c-b757-efdcf48c9efb)

![image](https://github.com/manimaul/njord/assets/81301702/7aaef8ed-ba24-4df9-aeb2-5f67f0cd8cf1)

**Comment by manimaul** [comment]
OpenCPN does the same thing here. Perhaps we could adjust how zoom is calculated here. However, it's always going to be a balance of displaying more and not cluttering the display. IMO opinion we shouldn't clutter the screen any more than it is now. 

Notice how cluttered OpenCPN is here using the default vector display settings. 
![Screenshot from 2024-11-30 10-20-03](https://github.com/user-attachments/assets/a1fd0750-e9d5-4d51-909c-7c447dfde3ef)

**Comment by manimaul** [comment]
I also think this is a data issue here. Let's see how coverage changes after NOAA rescheme's ENCs in this area:
https://distribution.charts.noaa.gov/ENC/rescheme/
