### ISSUE TITLE
Tiles respond slowly

### ISSUE THREAD

**Issue by echohye** [manimaul/njord#48]
This may not be a good method because it will traverse and query the entire features table, which may cause tile generation to be abnormally slow.
https://github.com/manimaul/njord/blob/73e3946d0e85b09b57158830934bb139498eb246/chart_server/src/main/kotlin/io/madrona/njord/db/FeatureDao.kt#L48

**Comment by manimaul** [comment]
Hi @echohye - yeah, this is definitely not ideal. Feel free to propose a solution. Perhaps lnam_refs can be added as an array on the features table with a [GIN index](https://www.postgresql.org/docs/current/indexes-types.html#INDEXES-TYPES-GIN). I think I want to avoid a foreign key setup as then insertion and deletion order matters. 

By the way - what kind of project are you working on?

**Comment by echohye** [comment]
In the BS architecture, I am more exposed to raster layers, and vector layers are still relatively rare. Vector layers have many advantages, and I think vector layers will dominate in the future. So I hope this project can do better.

**Comment by manimaul** [comment]
I'm closing this for now after adding GIN index. 
https://github.com/manimaul/njord/commit/3b1f49d0686a8f1f04666f952f5c1abe8404c23a
https://github.com/manimaul/njord/commit/3b1f49d0686a8f1f04666f952f5c1abe8404c23a
